FROM busybox:1.37
COPY deploy/monitoring/prometheus.yml /config/prometheus.yml
COPY deploy/monitoring/alert-rules.yml /config/alert-rules.yml
COPY deploy/monitoring/loki.yml /config/loki.yml
COPY deploy/monitoring/promtail.yml /config/promtail.yml
COPY deploy/monitoring/provisioning /config/grafana/provisioning
COPY deploy/monitoring/dashboards /config/grafana/dashboards
CMD ["sh", "-c", "cp -r /config/* /out/ && echo 'Config deployed'"]
